# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x16\n\x14GetLeaderInfoRequest\"%\n\x15GetLeaderInfoResponse\x12\x0c\n\x04info\x18\x01 \x01(\t\"1\n\x14SaveGameStateRequest\x12\x19\n\x11session_data_json\x18\x01 \x01(\t\"(\n\x15SaveGameStateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x16\n\x14LoadGameStateRequest\"Z\n\x15LoadGameStateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11session_data_json\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"\x1a\n\x07Version\x12\x0f\n\x07version\x18\x01 \x01(\t\"3\n\x0fVersionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x1dReplicateSaveGameStateRequest\x12\x19\n\x11session_data_json\x18\x01 \x01(\t\"1\n\x1eReplicateSaveGameStateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\r\n\x0bPingRequest\"\x1d\n\x0cPingResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32\xf9\x01\n\x0b\x43hatService\x12>\n\rGetLeaderInfo\x12\x15.GetLeaderInfoRequest\x1a\x16.GetLeaderInfoResponse\x12>\n\rSaveGameState\x12\x15.SaveGameStateRequest\x1a\x16.SaveGameStateResponse\x12>\n\rLoadGameState\x12\x15.LoadGameStateRequest\x1a\x16.LoadGameStateResponse\x12*\n\x0c\x43heckVersion\x12\x08.Version\x1a\x10.VersionResponse2o\n\x12ReplicationService\x12Y\n\x16ReplicateSaveGameState\x12\x1e.ReplicateSaveGameStateRequest\x1a\x1f.ReplicateSaveGameStateResponse2-\n\x06Health\x12#\n\x04Ping\x12\x0c.PingRequest\x1a\r.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLEADERINFOREQUEST']._serialized_start=14
  _globals['_GETLEADERINFOREQUEST']._serialized_end=36
  _globals['_GETLEADERINFORESPONSE']._serialized_start=38
  _globals['_GETLEADERINFORESPONSE']._serialized_end=75
  _globals['_SAVEGAMESTATEREQUEST']._serialized_start=77
  _globals['_SAVEGAMESTATEREQUEST']._serialized_end=126
  _globals['_SAVEGAMESTATERESPONSE']._serialized_start=128
  _globals['_SAVEGAMESTATERESPONSE']._serialized_end=168
  _globals['_LOADGAMESTATEREQUEST']._serialized_start=170
  _globals['_LOADGAMESTATEREQUEST']._serialized_end=192
  _globals['_LOADGAMESTATERESPONSE']._serialized_start=194
  _globals['_LOADGAMESTATERESPONSE']._serialized_end=284
  _globals['_EMPTY']._serialized_start=286
  _globals['_EMPTY']._serialized_end=293
  _globals['_VERSION']._serialized_start=295
  _globals['_VERSION']._serialized_end=321
  _globals['_VERSIONRESPONSE']._serialized_start=323
  _globals['_VERSIONRESPONSE']._serialized_end=374
  _globals['_REPLICATESAVEGAMESTATEREQUEST']._serialized_start=376
  _globals['_REPLICATESAVEGAMESTATEREQUEST']._serialized_end=434
  _globals['_REPLICATESAVEGAMESTATERESPONSE']._serialized_start=436
  _globals['_REPLICATESAVEGAMESTATERESPONSE']._serialized_end=485
  _globals['_PINGREQUEST']._serialized_start=487
  _globals['_PINGREQUEST']._serialized_end=500
  _globals['_PINGRESPONSE']._serialized_start=502
  _globals['_PINGRESPONSE']._serialized_end=531
  _globals['_CHATSERVICE']._serialized_start=534
  _globals['_CHATSERVICE']._serialized_end=783
  _globals['_REPLICATIONSERVICE']._serialized_start=785
  _globals['_REPLICATIONSERVICE']._serialized_end=896
  _globals['_HEALTH']._serialized_start=898
  _globals['_HEALTH']._serialized_end=943
# @@protoc_insertion_point(module_scope)
