# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import spotit_pb2 as spotit__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in spotit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpotItGameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/spotit.SpotItGameService/CreateGame',
                request_serializer=spotit__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=spotit__pb2.CreateGameResponse.FromString,
                _registered_method=True)
        self.JoinGame = channel.unary_unary(
                '/spotit.SpotItGameService/JoinGame',
                request_serializer=spotit__pb2.JoinGameRequest.SerializeToString,
                response_deserializer=spotit__pb2.JoinGameResponse.FromString,
                _registered_method=True)
        self.GetGameState = channel.unary_unary(
                '/spotit.SpotItGameService/GetGameState',
                request_serializer=spotit__pb2.GameStateRequest.SerializeToString,
                response_deserializer=spotit__pb2.GameStateResponse.FromString,
                _registered_method=True)
        self.PlayTurn = channel.unary_unary(
                '/spotit.SpotItGameService/PlayTurn',
                request_serializer=spotit__pb2.PlayTurnRequest.SerializeToString,
                response_deserializer=spotit__pb2.PlayTurnResponse.FromString,
                _registered_method=True)
        self.ListGames = channel.unary_unary(
                '/spotit.SpotItGameService/ListGames',
                request_serializer=spotit__pb2.ListGamesRequest.SerializeToString,
                response_deserializer=spotit__pb2.ListGamesResponse.FromString,
                _registered_method=True)


class SpotItGameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """Create a new game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGame(self, request, context):
        """Join an existing game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameState(self, request, context):
        """Get game state (cards, players, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayTurn(self, request, context):
        """Player plays a turn (clicks a match)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGames(self, request, context):
        """List active games
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpotItGameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=spotit__pb2.CreateGameRequest.FromString,
                    response_serializer=spotit__pb2.CreateGameResponse.SerializeToString,
            ),
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=spotit__pb2.JoinGameRequest.FromString,
                    response_serializer=spotit__pb2.JoinGameResponse.SerializeToString,
            ),
            'GetGameState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameState,
                    request_deserializer=spotit__pb2.GameStateRequest.FromString,
                    response_serializer=spotit__pb2.GameStateResponse.SerializeToString,
            ),
            'PlayTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayTurn,
                    request_deserializer=spotit__pb2.PlayTurnRequest.FromString,
                    response_serializer=spotit__pb2.PlayTurnResponse.SerializeToString,
            ),
            'ListGames': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGames,
                    request_deserializer=spotit__pb2.ListGamesRequest.FromString,
                    response_serializer=spotit__pb2.ListGamesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spotit.SpotItGameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spotit.SpotItGameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpotItGameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotit.SpotItGameService/CreateGame',
            spotit__pb2.CreateGameRequest.SerializeToString,
            spotit__pb2.CreateGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotit.SpotItGameService/JoinGame',
            spotit__pb2.JoinGameRequest.SerializeToString,
            spotit__pb2.JoinGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotit.SpotItGameService/GetGameState',
            spotit__pb2.GameStateRequest.SerializeToString,
            spotit__pb2.GameStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotit.SpotItGameService/PlayTurn',
            spotit__pb2.PlayTurnRequest.SerializeToString,
            spotit__pb2.PlayTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotit.SpotItGameService/ListGames',
            spotit__pb2.ListGamesRequest.SerializeToString,
            spotit__pb2.ListGamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
