# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spotit.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'spotit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspotit.proto\x12\x06spotit\"=\n\x11\x43reateGameRequest\x12\x13\n\x0bhost_player\x18\x01 \x01(\t\x12\x13\n\x0bnum_players\x18\x02 \x01(\x05\"6\n\x12\x43reateGameResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x0fJoinGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\"4\n\x10JoinGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x10GameStateRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"g\n\x11GameStateResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x14\n\x0cplayer_names\x18\x02 \x03(\t\x12\x1b\n\x05\x63\x61rds\x18\x03 \x03(\x0b\x32\x0c.spotit.Card\x12\x0e\n\x06status\x18\x04 \x01(\t\"`\n\x0fPlayTurnRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\x12\x12\n\ncard_index\x18\x03 \x01(\x05\x12\x13\n\x0b\x65moji_index\x18\x04 \x01(\x05\"f\n\x10PlayTurnResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x30\n\rupdated_state\x18\x03 \x01(\x0b\x32\x19.spotit.GameStateResponse\"\x12\n\x10ListGamesRequest\"%\n\x11ListGamesResponse\x12\x10\n\x08game_ids\x18\x01 \x03(\t\"\x16\n\x04\x43\x61rd\x12\x0e\n\x06\x65mojis\x18\x01 \x03(\t2\xdd\x02\n\x11SpotItGameService\x12\x43\n\nCreateGame\x12\x19.spotit.CreateGameRequest\x1a\x1a.spotit.CreateGameResponse\x12=\n\x08JoinGame\x12\x17.spotit.JoinGameRequest\x1a\x18.spotit.JoinGameResponse\x12\x43\n\x0cGetGameState\x12\x18.spotit.GameStateRequest\x1a\x19.spotit.GameStateResponse\x12=\n\x08PlayTurn\x12\x17.spotit.PlayTurnRequest\x1a\x18.spotit.PlayTurnResponse\x12@\n\tListGames\x12\x18.spotit.ListGamesRequest\x1a\x19.spotit.ListGamesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spotit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEGAMEREQUEST']._serialized_start=24
  _globals['_CREATEGAMEREQUEST']._serialized_end=85
  _globals['_CREATEGAMERESPONSE']._serialized_start=87
  _globals['_CREATEGAMERESPONSE']._serialized_end=141
  _globals['_JOINGAMEREQUEST']._serialized_start=143
  _globals['_JOINGAMEREQUEST']._serialized_end=198
  _globals['_JOINGAMERESPONSE']._serialized_start=200
  _globals['_JOINGAMERESPONSE']._serialized_end=252
  _globals['_GAMESTATEREQUEST']._serialized_start=254
  _globals['_GAMESTATEREQUEST']._serialized_end=289
  _globals['_GAMESTATERESPONSE']._serialized_start=291
  _globals['_GAMESTATERESPONSE']._serialized_end=394
  _globals['_PLAYTURNREQUEST']._serialized_start=396
  _globals['_PLAYTURNREQUEST']._serialized_end=492
  _globals['_PLAYTURNRESPONSE']._serialized_start=494
  _globals['_PLAYTURNRESPONSE']._serialized_end=596
  _globals['_LISTGAMESREQUEST']._serialized_start=598
  _globals['_LISTGAMESREQUEST']._serialized_end=616
  _globals['_LISTGAMESRESPONSE']._serialized_start=618
  _globals['_LISTGAMESRESPONSE']._serialized_end=655
  _globals['_CARD']._serialized_start=657
  _globals['_CARD']._serialized_end=679
  _globals['_SPOTITGAMESERVICE']._serialized_start=682
  _globals['_SPOTITGAMESERVICE']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
